image:
  repository: ghcr.io/home-operations/lidarr
  pullPolicy: IfNotPresent
  tag: 2.11.0.4610

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

lidarrConfig:
  instanceName: Lidarr
  additionalEnvs: []

lidarrNetwork:
  webPort: 30014
  hostNetwork: false

lidarrRunAs:
  user: 568
  group: 568

lidarrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
